Fixes for serverless HLS
opencast/annotation-tool pull request #627
Opened 2024-05-16 17:29 UTC by KatrinIhler

Actual changes from @luniki.

- Pefer master playlists over non-master playlists and mp4s
- Prefer native_hls renderer
- Wait for !isFinitite instead of isNan for this renderer

2024-09-05 13:24 UTC, JulianKniephoff requested changes

2024-09-05 13:24 UTC, JulianKniephoff commented on frontend/js/integrations/search.js
> +                videos = _.sortBy(videos, "master").reverse();
Can we integrate this in the `sort` below? Something like

```js
videos.sort(
    util.lexicographical([
        util.firstWith(
            _.property("master")
        ),
        // [...]
    ])
);
```

Should work, but please double-check me on this.

2024-09-05 13:24 UTC, JulianKniephoff commented on frontend/js/player-adapter-html5.js
> +                    renderers: ["native_hls", "html5"],
Is this necessary even with the correct sort order of the videos? 🤔

Looking at the docs for this setting I also wonder: Can we get away with not specifying this at all?

2024-09-05 13:24 UTC, JulianKniephoff commented on frontend/js/player-adapter-html5.js
> +                            if (!isFinite(self.getDuration()) || mediaElement.readyState < 1) {
Wouldn't live streams have infinite durations? 🤔 Although to be fair, the rest of the tool can't deal with those, either. x)

Still, I wonder: Did you encounter a case where the duration is infinite first, and then changes to something finite?

2024-09-05 13:27 UTC, JulianKniephoff commented
Pinging @luniki to look at this review since he is the original author of the patch IIRC.

2025-01-24 15:02 UTC, marwyg commented on frontend/js/player-adapter-html5.js
> +                    renderers: ["native_hls", "html5"],
I removed the `renderers` line. I read the documentation and this field doesn't seem mandatory. It still works when I removed it: https://github.com/opencast/annotation-tool/pull/646

2025-01-24 15:03 UTC, marwyg commented on frontend/js/player-adapter-html5.js
> +                            if (!isFinite(self.getDuration()) || mediaElement.readyState < 1) {
As mentioned in https://github.com/opencast/annotation-tool/pull/646, I didn't see such a case, but Marcus did, I don't know. But I compared in my other PR both functions (isNaN and !isFinite) and I think it should be okay like this.

2025-01-24 15:04 UTC, marwyg commented
I took the changes from here, addressed @JulianKniephoff review points and made my own PR https://github.com/opencast/annotation-tool/pull/646. Maybe someone can take a look again, I think this should be okay now.

2025-03-05 16:33 UTC, JulianKniephoff commented
Closing in favor of #646

2025-03-05 16:33 UTC, closed without merging