Fix wrong dcTitle key
opencast/annotation-tool pull request #637
Opened 2024-11-28 13:49 UTC by jduehring

This PR fixes https://github.com/opencast/annotation-tool/issues/633 . 

The structure of the field `result.dcTitle` changed at some point in OC, so that we need to call the sub-field `dc.title` .

2024-12-03 20:08 UTC, dagraf commented
It now works as expected. Thx for the fix!

2024-12-05 11:55 UTC, JulianKniephoff requested changes
This works, but looking at this part of the code more closely again, we could actually replace `getVideoParameters` with the following, which is a bit simpler **and** should be portable across the breaking changes to the search API:

```js
        getVideoParameters: function () {
            return mediaPackage.then(function (mediaPackage) {
                return {
                    video_extid: mediaPackage.id,
                    series_extid: mediaPackage.series,
                    title: mediaPackage.title,
                };
            });
        },
```

2024-12-09 09:56 UTC, jduehring commented
> This works, but looking at this part of the code more closely again, we could actually replace `getVideoParameters` with the following, which is a bit simpler **and** should be portable across the breaking changes to the search API:
> 
> ```js
>         getVideoParameters: function () {
>             return mediaPackage.then(function (mediaPackage) {
>                 return {
>                     video_extid: mediaPackage.id,
>                     series_extid: mediaPackage.series,
>                     title: mediaPackage.title,
>                 };
>             });
>         },
> ```

Agreed. I had this in mind as well but thought there was probably some deeper reason for getting the info from different fields, which I am overlooking :D Anyway, changed the code and it seems to work as expected.

2024-12-11 15:24 UTC, JulianKniephoff approved these changes

2024-12-11 15:24 UTC, merged